# Generated by Django 6.0.1 on 2026-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
