# Generated by Django 6.0.1 on 2026-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0002_alter_members_mobile_alter_members_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Mobile',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
