# Generated by Django 6.0.1 on 2026-01-12 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0003_alter_members_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_details',
            name='Plan',
        ),
        migrations.RemoveField(
            model_name='members_details',
            name='Total_Price',
        ),
        migrations.AddField(
            model_name='members',
            name='Address',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='Plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customapp.plans'),
        ),
        migrations.AlterField(
            model_name='members',
            name='user',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
