# Generated by Django 6.0.1 on 2026-01-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0004_remove_members_details_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Amount',
            field=models.FloatField(null=True),
        ),
    ]
