# Generated by Django 6.0.1 on 2026-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0005_members_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_a',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Member')], default=1),
        ),
    ]
